### PR TITLE
fix: #175 'native:migrate fresh' command does not work

### LINKED ISSUE #175: [Bug]: 'native:migrate fresh' does not work
### What happened?

By running `php artisan native:migrate fresh`, I expected the whole database schema to be refreshed and all data gone as explained in the docs.

### How to reproduce the bug

When I run the command, the output is as follows:

`No arguments expected for "native:migrate" command, got "fresh".`

### Package Version

0.4.0

### PHP Version

8.2.8

### Laravel Version

10.18.0

### Node Version

20.5.0

### Which operating systems does with happen with?

macOS

### Notes

_No response_

### PR DESCRIPTION
**Pull request by me-shaon**
Closes #175 

### Why
The previous implementation of `native:migrate fresh` command conflicted with the base `native:migrate` command implementation and showed the error described in the issue. 

### Changes
- Updated the `FreshCommand` implementation to extend it from the base `FreshCommand` of the Illuminate Console command and updated the signature to keep it similar to the base command. 
- Updated the `NativeServiceProvider` to add this new command.

### CODE REVIEW

**Comment by me-shaon** [comment]
@mpociot not sure why the tests are failing. Let me know if I need to fix anything in this PR.

**Comment by Phr33d0m** [comment]
Hi, any news on this one? It is quite the show-stopper.

**Comment by me-shaon** [comment]
@mpociot can you please take a look at it?

**Comment by LunashaGit** [comment]
> @mpociot not sure why the tests are failing. Let me know if I need to fix anything in this PR.

Hello ! 

I have the same issues,
BUT : 
I've done the tests in the local environment and everything's fine, because I've opened NativePHP ( which uses localhost:4000 ) and almost all the tests work, only one crashes ( Maybe because I'm on Windows, I'm not sure ).

-> https://github.com/NativePHP/laravel/pull/249

**Comment by simonhamp** [comment]
This looks fine. I just need to spend some time fixing the tests

**Comment by simonhamp** [comment]
Ok, I've been digging into the test failures and I think it's a slightly wider issue than we need to resolve here, so I'm going to merge this and fix the tests separately

**Pull request merged**
