### PR TITLE
Add Tests For `Windows`

### PR DESCRIPTION
**Pull request by milwad-dev**
Coverage is 100%, but just WindowManager can't write tests because didn't return anything

### CODE REVIEW

**Comment by pari-sadegh-80** [comment]
Are you a member of NativePHP?

**Comment by milwad-dev** [comment]
No, but it's a good idea

**Comment by milwad-dev** [comment]
@mpociot 
The workflow errors are about the guzzlehttp, we talked about this before!

**Comment by mpociot** [comment]
Thank you!

**Pull request merged**
